### ISSUE TITLE
statemachine race condition

### ISSUE THREAD

**Issue by yannickmorel** [rianwouters/cfn-customresources#2]
When running the ACM statemachine, there's an update to the statemachine content. (.promise().then()) however the first execution of the stepfunction can result in being called before the content of the statemachine has been updated with the new template.

**Comment by rianwouters** [comment]
I believe, allthough it is explicitly specified in the documentation, this is a bug in the AWS SDK design.
As there is no easy why to find out when the definition is updated, implemented a timeout:

https://github.com/rianwouters/cfn-customresources/commit/122ae2e846f62fba79fbbd31547055ce930b5fa1
